product list
anupkgurung/thebooklet-ecom pull request #5
Opened 2022-02-13 14:44 UTC by anupkgurung

2022-02-13 15:56 UTC, AurobindoGupta commented
nice work!!
sidenav looks a little cluttered preferably look into its spacing.

2022-02-13 16:48 UTC, AurobindoGupta approved these changes

2022-02-13 16:50 UTC, aniketsingh13 approved these changes
look good to me

2022-02-14 05:22 UTC, rajkishancode commented on style/homepage.css
> +.cateogory li input,
There's a typo ,you can correct this.

2022-02-14 05:24 UTC, rajkishancode approved these changes
Rest looks good .

2022-02-17 16:09 UTC, akshay-rajput requested changes
make these changes and ping me.

2022-02-17 16:09 UTC, akshay-rajput commented on page/productlist.html
> +        <div id="" class="header-bar">
remove id="" if not using it.

2022-02-17 16:09 UTC, akshay-rajput commented on page/productlist.html
> +                    <ul class="list-inline">
remove list-inline from ul

2022-02-17 16:09 UTC, akshay-rajput commented on page/productlist.html
> +        <div id="main" class="content-body">
use main tag here

2022-02-17 16:09 UTC, akshay-rajput commented on page/productlist.html
> +                        <div class='card-container card-container--verticle product-card-container'>
keep your css class name convention consistent

2022-02-17 16:09 UTC, akshay-rajput commented on page/productlist.html
> +                                    <img class="responsive img-radius position-abs" src="../image/book/digitphototwo.jpg" alt="The Digital Photography vol-II">
if possible use webp images. look up the support for webp though

2022-02-17 16:09 UTC, akshay-rajput commented on style/homepage.css
> +    height: 18.7rem;
giving fix height or width might create issues with responsiveness. try to find a better way to achieve what you want

2022-02-19 18:38 UTC, merged